replicaCount: 1
image:
  repository: marclucchini/notifications-service
  tag: latest
  pullPolicy: Always
service:
  name: notifications-service
  type: ClusterIP
  externalPort: 80
  internalPort: 8080
resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi
