version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - users-mongodb
  users-mongodb:
    image: mongo:3.4
    ports:
      - "27017:27017"
    command: mongod --smallfiles
